name: PR to main

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-ts:
    runs-on: ubuntu-latest
    name: Check TypeScript
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-ts
      - uses: ./.github/actions/check-ts
